# Modified by @shakida
# fastest microsoft server upto 3gbps
# 6 hr uptime by GitHub
# easy way to host mirror bots
name: Xmirror

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values
  GitHubMail: "tollerdl.1234@gmail.com"
  GitHubName: "shakida" 
  Branch: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup env
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.TOKEN }}@github.com" > ~/.git-credentials
      - name: Duplicate workflows cancelling
        uses: styfle/cancel-workflow-action@0.9.0
        with:
           all_but_latest: true
           access_token: ${{ secrets.TOKEN }}
      - name: Cleanup storage
        run: |
          curl -sL https://raw.githubusercontent.com/ahadz-git/testwf/main/cleanup -o cleanup.sh && chmod +x cleanup.sh
          sudo sh cleanup.sh
      - name: Cloning the repo
        run: |
          git clone https://${GitHubName}:${{ secrets.TOKEN }}@github.com/${{ secrets.MIRROR_REPO }} -b ${Branch} source

      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker image ls

      - name: Running ðŸŸ¢
        timeout-minutes: 340 
        continue-on-error: true
        run: |
          docker run --privileged --rm -i mirror-bot

      - name: Run looping
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Run Looping ðŸŸ¢"
          git push -q https://${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
